name = "AutoTuningGMD"
uuid = "634b6fbe-6ad4-43d9-92dd-b3cd32515657"
authors = ["tduretz <duretz@uni-frankfurt.de>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CellArrays = "d35fcfd7-7af4-4c67-b1aa-d78070614af4"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JustPIC = "10dc771f-8528-4cd9-9d3b-b21b2e693339"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MathTeXEngine = "0a4f8689-d25c-4efe-a92b-7142dfc1aa53"
ParallelStencil = "94395366-693c-11ea-3b26-d9b7aac5d958"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
CairoMakie = "0.15.6"
CellArrays = "0.3.2"
JLD2 = "0.6.2"
JustPIC = "0.5.11"
LinearAlgebra = "1.11.0"
Makie = "0.24.6"
MathTeXEngine = "0.6.7"
ParallelStencil = "0.14.3"
Plots = "1.41.1"
Printf = "1.11.0"
StaticArrays = "1.9.15"
Statistics = "1.11.1"
TimerOutputs = "0.5.29"
WriteVTK = "1.21.2"
